#  Copyright 2021 The casbin Authors. All Rights Reserved.

#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: Memcheck

on: [push, pull_request]

jobs:
  linux:
    name: "Ubuntu Latest (GNU 9.3.0)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Install requirement
        id: install-requirements
        run: |
          sudo apt-get update
          sudo apt-get install valgrind
      - name: Configuring CMake files
        id: building-files
        run: |
          mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
      - name: Building library
        id: building-lib
        run: |
          cd build && cmake --build . --config Release --target all -j 10 --
      - name: Memcheck
        id: memcheck
        run: |
          cd build
          ctest -j10 -C Release -T MemCheck --output-on-failure
      - name: Cleanup
        id: clean-up
        run: |
          rm -r build
